### ISSUE TITLE
Give few hints on how to use jupytext

### ISSUE THREAD

**Issue by pierrepo** [Thibault-Poinsignon/Network#2]
It looks like jupytext is used on this project.

Could you provide few hints on how to use it, as well as essential instructions to rebuild `.ipynb` from `.py`?

**Comment by Thibault-Poinsignon** [comment]
Did the update on the Readme doc answered your question ?

**Comment by pierrepo** [comment]
Yes. Thanks.

**Comment by Thibault-Poinsignon** [comment]
You're welcome.
